CREATE TABLE IF NOT EXISTS account (
    account_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS pets (
    pet_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pet_name CHARACTER VARYING NOT NULL,
    pet_breed CHARACTER VARYING NOT NULL,
    pet_age INT NOT NULL,
    pet_lastvetvisit DATE,
    pet_vaccinated_id INT NOT NULL,
    account_id INT NOT NULL,
    CONSTRAINT account_fk FOREIGN KEY (account_id) REFERENCES account(account_id),
    CONSTRAINT pet_pk PRIMARY KEY (pet_id)
);

CREATE TABLE IF NOT EXISTS vaccine (
    vaccine_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vaccine_name CHARACTER VARYING NOT NULL,
    CONSTRAINT vaccine_pk PRIMARY KEY (vaccine_id)
);

CREATE TABLE IF NOT EXISTS vaccinated (
    vaccinated_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vaccinated_date DATE NOT NULL,
    vaccine_id INT NOT NULL,
    pet_id INT NOT NULL,
    CONSTRAINT pet_fk FOREIGN KEY (pet_id) REFERENCES pets(pet_id),
    CONSTRAINT vaccinated_pk PRIMARY KEY (vaccinated_id)
);

-- ALTER TABLE IF EXISTS pets
-- ADD CONSTRAINT fk_vaccinated FOREIGN KEY (pet_vaccinated_id) REFERENCES vaccinated(vaccinated_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

-- ALTER TABLE IF EXISTS vaccinated
-- ADD CONSTRAINT vaccine_fk FOREIGN KEY (vaccine_id) REFERENCES vaccine(vaccine_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

-- ALTER TABLE IF EXISTS account
-- ADD CONSTRAINT un_account_email UNIQUE (account_email);

INSERT INTO vaccine (vaccine_name) VALUES 
    ('Rabies'), 
    ('DHPP'), 
    ('Leptospirosis'), 
    ('Bordetella'), 
    ('Lyme Disease'), 
    ('Canine Influenza'),
    ('FVRCP'),
    ('Feline Leukemia Virus'),
    ('Feline Immunodeficiency Virus'),
    ('Chlamydophila');

CREATE TABLE IF NOT EXISTS image (
    image_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    image_path CHARACTER VARYING NOT NULL,
    account_id INT NOT NULL,
    CONSTRAINT image_pk PRIMARY KEY (image_id)
);

ALTER TABLE IF EXISTS pets 
ADD IF NOT EXISTS image_id INT NOT NULL;

ALTER TABLE IF EXISTS pets 
ADD IF NOT EXISTS pet_weight INT NOT NULL;

ALTER TABLE IF EXISTS pets 
ALTER COLUMN pet_vaccinated_id DROP NOT NULL;

-- ALTER TABLE IF EXISTS image
-- RENAME image_path TO image_name;


ALTER TABLE IF EXISTS vaccinated DROP CONSTRAINT pet_fk,
ADD CONSTRAINT pet_fk FOREIGN KEY (pet_id) REFERENCES pets(pet_id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS feedback (
    feedback_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    feedback_body TEXT NOT NULL,
    CONSTRAINT check_min_text_length CHECK (LENGTH(feedback_body) >= 16),
    CONSTRAINT account_fk FOREIGN KEY (account_id) REFERENCES account(account_id) ON DELETE CASCADE,
    CONSTRAINT feedback_fk PRIMARY KEY (feedback_id)
)