CREATE TABLE IF NOT EXISTS public.account (
    account_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public.pets (
    pet_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pet_name CHARACTER VARYING NOT NULL,
    pet_breed CHARACTER VARYING NOT NULL,
    pet_age INT NOT NULL,
    pet_lastvetvisit DATE,
    pet_vaccinated_id INT NOT NULL,
    account_id INT NOT NULL,
    CONSTRAINT account_fk FOREIGN KEY (account_id) REFERENCES public.account(account_id),
    CONSTRAINT pet_pk PRIMARY KEY (pet_id)
);

CREATE TABLE IF NOT EXISTS public.vaccine (
    vaccine_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vaccine_name CHARACTER VARYING NOT NULL,
    CONSTRAINT vaccine_pk PRIMARY KEY (vaccine_id)
);

CREATE TABLE IF NOT EXISTS public.vaccinated (
    vaccinated_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vaccinated_date DATE NOT NULL,
    vaccine_id INT NOT NULL,
    pet_id INT NOT NULL,
    CONSTRAINT pet_fk FOREIGN KEY (pet_id) REFERENCES public.pets(pet_id),
    CONSTRAINT vaccinated_pk PRIMARY KEY (vaccinated_id)
);

ALTER TABLE IF EXISTS public.pets
ADD CONSTRAINT fk_vaccinated FOREIGN KEY (pet_vaccinated_id) REFERENCES public.vaccinated(vaccinated_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.vaccinated
ADD CONSTRAINT vaccine_fk FOREIGN KEY (vaccine_id) REFERENCES public.vaccine(vaccine_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.account
ADD CONSTRAINT un_account_email UNIQUE (account_email);

INSERT INTO public.vaccine (vaccine_name) VALUES 
    ('Rabies'), 
    ('DHPP'), 
    ('Leptospirosis'), 
    ('Bordetella'), 
    ('Lyme Disease'), 
    ('Canine Influenza'),
    ('FVRCP'),
    ('Feline Leukemia Virus'),
    ('Feline Immunodeficiency Virus'),
    ('Chlamydophila');

CREATE TABLE IF NOT EXISTS public.image (
    image_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    image_path CHARACTER VARYING NOT NULL,
    account_id INT NOT NULL,
    CONSTRAINT image_pk PRIMARY KEY (image_id)
);

ALTER TABLE IF EXISTS public.pets 
ADD IF NOT EXISTS image_id INT NOT NULL;

ALTER TABLE IF EXISTS public.pets 
ADD IF NOT EXISTS pet_weight INT NOT NULL;

ALTER TABLE IF EXISTS public.pets 
ALTER COLUMN pet_vaccinated_id DROP NOT NULL;

ALTER TABLE IF EXISTS public.image
RENAME image_path TO image_name;
